var_secure_boot: true
# var_cryptenroll_tpm2_pcrs: 0+2+7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000
var_cryptenroll_tpm2_pcrs: 7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000
var_cryptenroll_tpm2_pubkey_pcrs: "11"
# var_cryptenroll_tpm2_pubkey_pcrs: ""
var_uki_filename: linux-uki-signed-2025111702.efi
var_uki_artifact: https://api.github.com/repos/skosachiov/remediations-gendbuntu/actions/artifacts/4586663166/zip
var_token_head: github_pat_
var_token_tail: 11ABI7QAI0Noo5mutnfZ7t_qO6kZRccqCW93vrjE7qsSTusFSrKZxiEZu0AldKvQogK7D2CQLMenfTgsns
var_sec_officer_pubkey: https://github.com/skosachiov/remediations-gendbuntu/raw/main/assets/sample-pubkey.asc
var_crypt_unlock_key_file: /root/unlock-key-file.weak
var_crypt_recovery_key: /root/recovery-key.strong
