var_secure_boot: true
# var_cryptenroll_tpm2_pcrs: 0+2+7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000
var_cryptenroll_tpm2_pcrs: 7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000
var_uki_filename: linux-uki-signed-20251108.efi
var_token_head: github_pat_
var_sec_officer_pubkey: https://github.com/skosachiov/remediations-gendbuntu/raw/main/assets/sample-pubkey.asc