var_secure_boot: true
var_cryptenroll_tpm_pcrs: 0+2+7+15:sha256=0000000000000000000000000000000000000000000000000000000000000000
var_uki_filename: linux-uki-signed-20251106.efi
var_token_head: github_pat_