version: '3.8'

services:
  apache:
    env_file:
      - .env
    image: ${IMAGE}
    build: ./apache
    container_name: apache
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host

  uki-builder:
    env_file:
      - .env
    image: ${IMAGE}
    build: ./uki-builder
    container_name: uki-builder
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
