version: '3.8'

services:
  apache:
    env_file:
      - .env
    build:
      context: ./apache
      dockerfile: Dockerfile
      args:
        - IMAGE=${IMAGE}
    container_name: apache
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
    command: >
      /bin/bash -c "
      sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf &&
      apache2ctl -D FOREGROUND
      "

  uki-builder:
    env_file:
      - .env
    build:
      context: ./uki-builder
      dockerfile: Dockerfile
      args:
        - IMAGE=${IMAGE}      
    container_name: uki-builder
    volumes:
      - /tmp/html:/var/www/html
      - /tmp/workspace:/workspace
      - ../../../lcm:/lcm
    network_mode: host
    command: >
      /bin/bash -c "
      cp -f /lcm/assets/preseed.cfg; 
      cd /lcm/assets/esl;
      export SB_DB_KEY=$(cat DB.key);
      export PCR_PRIVATE_KEY_INITRD=$(cat tpm2-pcr-private-key-initrd.key);
      export PCR_PRIVATE_KEY_SYSTEM=$(cat tpm2-pcr-private-key-system.key);
      cd /lcm;
      assets/build-signed-uki.sh;
      cp -f /lcm/artifacts/* /var/www/html/;
      zip -A -j /var/www/html/zip /var/www/html/*
      "
