version: '3.8'

services:
  apache:
    env_file:
      - .env
    build:
      context: ./apache
      dockerfile: Dockerfile
      args:
        - IMAGE=${IMAGE}
    container_name: apache
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
    command: ["apache2ctl", "-D", "FOREGROUND"]

  uki-builder:
    env_file:
      - .env
    build:
      context: ./uki-builder
      dockerfile: Dockerfile
      args:
        - IMAGE=${IMAGE}      
    container_name: uki-builder
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
    command: ["../build-signed-uki.sh"]
