version: '3.8'

services:
  apache:
    env_file:
      - .env
    build:
      context: ./apache
      dockerfile: Dockerfile
    image: ${IMAGE}
    container_name: apache
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host

  uki-builder:
    env_file:
      - .env
    build:
      context: ./uki-builder
      dockerfile: Dockerfile
    image: ${IMAGE}
    container_name: uki-builder
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
