version: '3.8'

services:
  apache:
    env_file:
      - .env
    image: ${IMAGE}
    container_name: apache
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
    restart: 'no'

  uki-builder:
    env_file:
      - .env
    image: ${IMAGE}
    container_name: uki-builder
    volumes:
      - /tmp/html:/var/www/html
    network_mode: host
    restart: 'no'
