name: debian-12

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  ansible-check:
    runs-on: ubuntu-latest
    container: debian:12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - run: apt update
      - run: apt -y install python3-apt
      - run: apt -y install ansible
      - run: ansible-playbook -b --check --connection=local -i 127.0.0.1, workstation.yml
 