name: rocky-10

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  ansible-check:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:10
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - run: dnf -y install epel-release --nogpgcheck
      - run: dnf -y install openssh-server --nogpgcheck
      - run: dnf -y install ansible-core ansible-collection-community-general --nogpgcheck
      - run: dnf -y install ansible-collection-ansible-posix --nogpgcheck
      - run: ansible-playbook -b --check --connection=local -i 127.0.0.1, workstation.yml
